# This is a config for E2B sandbox template.
# You can use template ID (oemwi4t3adjnitsyzbg3) or template name (lovable-clone-dev) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox.create("lovable-clone-dev") # Sync sandbox
# sandbox = await AsyncSandbox.create("lovable-clone-dev") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('lovable-clone-dev')

team_id = "1d3d99a0-5d72-40fe-98fa-af41eefacf6f"
start_cmd = "cd /home/user/app && npm run dev"
dockerfile = "e2b.Dockerfile"
template_name = "lovable-clone-dev"
template_id = "oemwi4t3adjnitsyzbg3"
